---
- name: "check if agent certs exist"
  stat: "path={{ flocker_local_tempdir }}/{{ inventory_hostname }}-node.crt"
  delegate_to: 127.0.0.1
  register: agent_crt

- name: remove old /tmp/<clustername>/<node>
  command: rm -rf "{{ flocker_local_tempdir }}/{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  when: agent_crt.stat.exists == False

- name: create the directories to hold the agent certs
  file:
    path: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}"
    state: directory
  delegate_to: 127.0.0.1
  when: agent_crt.stat.exists == False

- name: gather ec2 facts for agent.yml template (aws)
  action: ec2_facts
  when: flocker_agent_backend == 'aws'

- name: copy agent.yml to the node via template (aws)
  sudo: yes
  template:
    src: aws/flocker-agent.yml.j2
    dest: /etc/flocker/agent.yml
  when: flocker_agent_backend == 'aws'

- name: copy agent.yml to the node
  copy: src={{ flocker_agent_yml_path }} dest=/etc/flocker/agent.yml owner=root
  sudo: yes
  when: (flocker_agent_backend is undefined or flocker_agent_backend is none or flocker_agent_backend | trim == '') and not (flocker_agent_yml_path is undefined or flocker_agent_yml_path is none or flocker_agent_yml_path | trim == '')

- name: create the node certs on the local machine
  shell: "flocker-ca create-node-certificate --outputpath={{ flocker_local_tempdir }}/{{ inventory_hostname }}/"
  args:
    chdir: "{{ flocker_local_tempdir }}"
  delegate_to: 127.0.0.1
  when: agent_crt.stat.exists == False

- name: copy cluster.crt to the node
  copy:
    src: "{{ flocker_local_tempdir }}/cluster.crt"
    dest: /etc/flocker/cluster.crt
  sudo: yes

- name: rename the node cert
  copy:
    src: "{{ item }}"
    dest: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-node.crt"
  with_fileglob: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}/*.crt"
  delegate_to: 127.0.0.1
  when: agent_crt.stat.exists == False

- name: rename the node key
  copy:
    src: "{{ item }}"
    dest: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-node.key"
    mode: 0600
  with_fileglob: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}/*.key"
  delegate_to: 127.0.0.1
  when: agent_crt.stat.exists == False

- name: copy the node cert to the correct agent node
  copy:
    src: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-node.crt"
    dest: /etc/flocker/node.crt
  sudo: yes
  notify:
    - restart flocker-dataset-agent
    - restart flocker-container-agent

- name: copy the key to the correct agent node
  copy:
    src: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-node.key"
    dest: /etc/flocker/node.key
    mode: 0600
  sudo: yes
  notify:
    - restart flocker-dataset-agent
    - restart flocker-container-agent