---
- stat: "path={{ flocker_local_tempdir }}/{{ inventory_hostname }}-plugin.crt"
  register: plugin_crt

- name: create the plugin certs on the local machine
  shell: "flocker-ca create-api-certificate {{ inventory_hostname }}-plugin"
  args:
    chdir: "{{ flocker_local_tempdir }}"
  delegate_to: 127.0.0.1
  when: plugin_crt.stat.exists == False

- name: copy the plugin cert to the correct agent node
  copy:
    src: "{{ item }}"
    dest: /etc/flocker/plugin.crt
  with_fileglob: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-plugin.crt"
  sudo: yes

- name: copy the plugin key to the correct agent node
  copy:
    src: "{{ item }}"
    dest: /etc/flocker/plugin.key
    mode: 0600
  with_fileglob: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-plugin.key"
  notify:
    - restart flocker-docker-plugin
  sudo: yes