---
- name: "check if plugin certs exist"
  stat: "path={{ flocker_local_tempdir }}/{{ inventory_hostname }}-plugin.crt"
  delegate_to: 127.0.0.1
  register: plugin_crt

- name: create the plugin certs on the local machine
  shell: "flocker-ca create-api-certificate {{ inventory_hostname }}-plugin"
  args:
    chdir: "{{ flocker_local_tempdir }}"
  delegate_to: 127.0.0.1
  when: plugin_crt.stat.exists == False

- name: copy the plugin cert to the correct agent node
  copy:
    src: "{{ item }}"
    dest: /etc/flocker/plugin.crt
  with_fileglob: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-plugin.crt"
  register: plugin_cert
  sudo: yes

- name: restart flocker docker plugin after plugin cert change
  when: plugin_cert.changed
  notify:
    - restart flocker-docker-plugin
  sudo: yes

- name: copy the plugin key to the correct agent node
  copy:
    src: "{{ item }}"
    dest: /etc/flocker/plugin.key
    mode: 0600
  with_fileglob: "{{ flocker_local_tempdir }}/{{ inventory_hostname }}-plugin.key"
  register: plugin_key
  sudo: yes

- name: restart flocker docker plugin after plugin key change
  when: plugin_key.changed
  notify:
    - restart flocker-docker-plugin
  sudo: yes