---
- name: install flocker-container-agent
  sudo: yes
  template:
    src: flocker-container-agent.service.j2
    dest: /etc/systemd/system/flocker-container-agent.service
  notify:
    - reload systemd
    - restart flocker-container-agent
  when: "'{{ flocker_agents_groupname }}' in group_names"

- name: install flocker-dataset-agent
  sudo: yes
  template:
    src: flocker-dataset-agent.service.j2
    dest: /etc/systemd/system/flocker-dataset-agent.service
  notify:
    - reload systemd
    - restart flocker-dataset-agent
  when: "'{{ flocker_agents_groupname }}' in group_names"

- name: install flocker-control
  sudo: yes
  template:
    src: flocker-control.service.j2
    dest: /etc/systemd/system/flocker-control.service
  notify:
    - reload systemd
    - restart flocker-control
  when: "'{{ flocker_control_service_groupname }}' in group_names"
  run_once: true

- name: create docker plugins dir
  sudo: yes
  file:
    path: "/run/docker/plugins"
    state: directory
  delegate_to: 127.0.0.1
  when: "flocker_install_docker_plugin and '{{ flocker_agents_groupname }}' in group_names"

- include: configure_flocker_docker_plugin.yml
  when: "flocker_install_docker_plugin and '{{ flocker_agents_groupname }}' in group_names"

- name: install flocker-docker-plugin
  sudo: yes
  template:
    src: flocker-docker-plugin.service.j2
    dest: /etc/systemd/system/flocker-docker-plugin.service
  notify:
    - reload systemd
    - restart flocker-docker-plugin
  when: "flocker_install_docker_plugin and '{{ flocker_agents_groupname }}' in group_names"

